### ISSUE TITLE
Intregrate Ploomber-Engine to Ploomber

### ISSUE THREAD

**Issue by mehtamohit013** [ploomber/ploomber#1082]
Introduce an engine parameter `engine:`, to let users select between papermill and ploomber-engine. Also add the documentation to it.

This will also allow user to display inline progress bar #1080 

Some Context: [Comment](https://github.com/ploomber/ploomber-engine/issues/68#issuecomment-1477094502)

**Comment by edublancas** [comment]
Bear in mind that there will be conflicting options. If the user passes `engine: ploomber-engine`, then the field `papermill_params` should not be allowed.

I'm thinking that we can rename `papermill_params` to `nb_executor_params` so it works with both ploomber-engine and papermill.

But to prevent breaking the API, we can display a FutureWarning telling users that `papermill_params` will be deprecated and they should use `nb_executor_params` instead.

**Comment by edublancas** [comment]
example: https://docs.ploomber.io/en/latest/user-guide/parametrized.html#Spec-API-(pipeline.yaml)

**Comment by edublancas** [comment]
Following up @mehtamohit013's questions from Slack:

> according to the [comment](https://github.com/ploomber/ploomber-engine/issues/68#issuecomment-1477094502), you mentioned ploomber uses ploomber-engine for debugging, but as far as I have understood, it still uses the [papermill-engine](https://github.com/ploomber/ploomber/blob/2a6287f1beea9f51ecbe59ddebac266cef6c77e8/src/ploomber/tasks/notebook.py#L776).

You're right. To fully explain, you need some extra background. papermill has a plugin system to add new "engines" which can customize how to run notebooks: you provide some basic logic, and papermill wraps this logic. When we first started developing ploomber-engine, we exclusively papermill extension, you can see that in the setup.py we're registering new [papermill engines](https://github.com/ploomber/ploomber-engine/blob/bedea73c84d428d580914747d36dd6885c2ac3dd/setup.py#L97) (that's why it's called ploomber-engine)

However, we then realized that offering a drop-in replacement for papermill was better so users could change the import instead of figuring out these papermill engines plugin system.

In consequence, there are two ways for users to run notebooks with papermill: 1. as a papermill engine (ie calling `papermill_execute_notebook` with the `engine_name` argument) and 2. by calling `from ploomber_engine import execute notebook; execute_notebook(...)`. The first option is already implemented (but undocumented), as you can see [here](https://github.com/ploomber/ploomber/blob/2a6287f1beea9f51ecbe59ddebac266cef6c77e8/src/ploomber/tasks/notebook.py#L768), if users pass the `debug_mode` option, we set the `engine_name` option for papermill.

What we want now is to enable the second option, and let users call `ploomber_engine.execute_notebook` directly.

> Also, ploomber engine doesn't support --debug and only supports --debuglater . So, I have to first add support for ploomber-engine in ploomber and then add support for debugging?

Yeah, the names of the arguments might not be the same, so we have to make some changes here.

> Also, I have found some reference to ploomber-engine [here](https://github.com/ploomber/ploomber/blob/2a6287f1beea9f51ecbe59ddebac266cef6c77e8/src/ploomber/micro/_capture.py#L14).

You can ignore this. It's an experimental API that we'll deprecate.

**Comment by edublancas** [comment]
once the new PR is created, I'll share my feedback
