### ISSUE TITLE
Do all tasks need to have a product?

### ISSUE THREAD

**Issue by fferegrino** [ploomber/ploomber#312]
Do all tasks need to have a product as output? I was thinking of steps (or tasks in Ploomber terminology) that do not have a explicit output, for example when we are registering a model in MLflow, or to trigger some action in an external system. I tried removing the `product` key and while it seems to work on the surface, I got this error in my Jupyter server console:

```
KeyError: "Error validating TaskSpec({'source': 'tasks.ignored_function', 'upstream': None}). Missing keys: {'product'}"
```

**Comment by edublancas** [comment]
Hi,

Yes. Tasks required at least one product because they serve as checkpoints so next time you build the pipeline, Ploomber only executes tasks whose source code has changed.

If you need to perform some extra actions you have two options.

1. Execute the code at the end of the Python function/script or notebook
2. Use the `on_finish` hook, which executes a function after the task is done

An `on_finish` hook is a function that takes the product as a parameter. Say your task looks like this:

```yaml
tasks:
   # this can be a script or a notebook
  - source: functions.train_model
    product: model.pickle
   # this must be a function
    on_finish: functions.register_model
```

The code:

```python
from pathlib import Path
import pickle

def train_model(product):
    # train model...
    Path(product).write_bytes(pickle.dumps(my_model))

def register_model(product):
    my_model = Path(product).read_bytes()
    # call mlflow here
```

[Here's a complete `on_finish` example](https://github.com/ploomber/projects/blob/master/testing/pipeline.yaml)

The current limitation of the `on_finish` hook is that it only takes the `product` as argument, if you need other variables to call mlflow, it's best to register the model in the task's code.

Let me know if this helps!

**Comment by fferegrino** [comment]
Cool, seems kind of what I was looking for.
