### ISSUE TITLE
Why do I need to call "build" to execute the pipeline?

### ISSUE THREAD

**Issue by fferegrino** [ploomber/ploomber#313]
Maybe a petty and minor issue, but I feel the name is a bit misleading. "build" sounds like it is trying to construct the pipeline and assessing whether is a valid pipeline or not, but in reality it executes the pipeline. To me, `execute` makes more sense.

Is there a particular reason `build` was chosen?

**Comment by edublancas** [comment]
The "incremental builds" term is somewhat [mainstream](https://docs.microsoft.com/en-us/visualstudio/msbuild/incremental-builds?view=vs-2019). For example, Make "builds software incrementally" by keeping track of source code changes, and most people understand that concept so I wanted to re-use the same terminology. So you could say "Ploomber builds pipelines incrementally".

**Comment by fferegrino** [comment]
I'd say that the key term (and the mainstream one) is "incremental" on its own, such as in [incremental learning](https://en.wikipedia.org/wiki/Incremental_learning), [incremental computing](https://en.wikipedia.org/wiki/Incremental_computing) and [incremental backup](https://en.wikipedia.org/wiki/Incremental_backup). 

To me you could still say "ploomber executes pipelines incrementally" which to me sounds more natural w.r.t. the action that happens when you call the "build" command. 

Talking to some colleagues I told them: "So I finished building the pipeline in this YAML file along with the code in this Python file, now I will head over to the console to execute it with ploomber... build".

**Comment by edublancas** [comment]
Yeah, I agree. You can make a case of why "build" may confuse people. At some point, I thought of changing it to something like run or execute but the internal codebase already has a "run" method.

In the `Task` implementation, `run` means "execute independently of all conditions", while `build` means "execute if the task is outdated, otherwise do not do anything". I could've made changes to accommodate for the run/build switch but it felt unnecessary.

In any case, thanks for the feedback. These kinds of wording details come up only after people actually start using a library (which is great!), so I don't discard making these types of changes in future major releases.

**Comment by fferegrino** [comment]
Coolio. Yeah, just suggesting. Will close this issue, but I'll keep an eye to see if something can be done about it in the future.
