### ISSUE TITLE
How to run the same task on different upstream dependencies?

### ISSUE THREAD

**Issue by rdmolony** [ploomber/ploomber#344]
Hey, thanks in advance for your time :)

I have some function ...

```python
def myfunction(
    upstream: Any, product: Any
) -> None:
    x = pd.read_csv(upstream["option1"] )
    # do something
    x.to_csv(product)
```
... that works on on different upstream dependencies `upstream["option1"]` and `upstream["option2"]`

What's the `ploomber` best practice for this?

---

Should I create a separate function for each regardless like ...

```python
def _mylogic():
   # do something

def myfunction_option1(
    upstream: Any, product: Any
) -> None:
    x = pd.read_csv(upstream["option1"] )
    _mylogic(x)
    x.to_csv(product)

def myfunction_option2(
    upstream: Any, product: Any
) -> None:
    x = pd.read_csv(upstream["option2"] )
    _mylogic(x)
    x.to_csv(product)
```

... or is there a way I might make the function independent from its upstream dependency definition?

---

Btw is `Github` your preferred place for saving and finding answers usage Qs like above?  I have just about enough rep to make a `ploomber` tag on `stackoverflow` too

**Comment by edublancas** [comment]
You have two choices:

1. If your pipeline, isn't large (I'd say <10 tasks), you can set `extract_upstream: False` and manually declare upstream dependencies in `pipeline.yaml`. Then, in your `myfunction`, use `upstream.first` instead of explicitly referring to the upstream dependency by name. (see  [proj.zip](https://github.com/ploomber/ploomber/files/7254408/proj.zip) for a minimal example)

2. Abstract the logic in a separate function (just like you did in your example with `_mylogic`)

But now you got me thinking. Right now the `extract_upstream` turns on/off globally. Maybe we should allow some tasks to declare upstream dependencies explicitly and keep the rest to be inferred automatically. 🤔

Regarding stack overflow, I think we'll want to move questions there. But probably a few months down the road. It's fine to post questions here at the moment.

**Comment by rdmolony** [comment]
Wonderful, thanks Eduardo :)
