### ISSUE TITLE
Integration with Sagemaker

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#424]
By adding an integration with the Jupyter package managers we can have more use cases covered, there are 2 approaches here and the generic one is preferred.

1. Create a boostrap script for each, either via docker or shell, install ploomber on start.
2. Create a mechanism to automatically integrate with the save option within the distribution and allow the users save their notebooks as scripts (instead of the current right click and open as a notebook).

**Comment by fferegrino** [comment]
Just curious about what about SageMaker you are talking about here? SageMaker Studio or SageMaker Notebook Instances?

**Comment by idomic** [comment]
Great question @fferegrino so this story is on SM Notebook instances. We'll probably want to make the solution generic enough so we can support both among other distributions. Wanna give it a try?

**Comment by fferegrino** [comment]
So I work with both in my daily job, both of them offer now Lifecycle Configurations where any user can install extensions their NB instance, so far that's how I am planning to get Ploomber up and running in SageMaker.

Now, reading the initial issue, it seems what you propose is being able to install Ploomber from within Jupyter itself? 

Happy to give it a try, regardless.

**Comment by edublancas** [comment]
Hi @fferegrino, thanks for helping us with this.

There are two things that *may not* work outside JupyterLab (e.g., VSCode, SageMaker, etc):

1. We encourage users to use `.py` files as task sources because that makes version control with git a lot easier. In JupyterLab, users can do right click -> open with -> notebook and the `.py` file will open as if it was a `.ipynb` file
2. Cell injection. When users open a notebook, we inject a new cell with information from  `pipeline.yaml` so they don't have to hardcode input and output paths

Both features are implemented as a [Jupyter plug-in](https://github.com/ploomber/ploomber/blob/master/src/ploomber/jupyter/manager.py).

My guess is that these two features *may work* in some platforms if:

1. The platform is simply a hosted JupyterLab - this is the case with Domino, for example
2. or it's a custom JupyterLab distribution but they leave the plug-in system intact

I've never used SageMaker notebooks, but based [on this video](https://docs.aws.amazon.com/sagemaker/latest/dg/nbi.html) it looks like they're simply a hosted JupyterLab, so Ploomber may actually work without changes.

Please let us know if that's the case, and if you encounter any issues when setting it up, we're happy to help.

**Comment by idomic** [comment]
Right, I believe after testing, we'll come into a conclusion that we need a bootstrap script to initialize Ploomber as part of the SM instance (those plug-ins are running when the server starts) and that's why I believe a user sh script to install Ploomber can solve it.

**Comment by fferegrino** [comment]
I don't think there is any need for code changes/additions to Ploomber, if anything some tutorial showing how to install/activate, I will confirm this throughout the week.

**Comment by edublancas** [comment]
Awesome, thanks! Please keep us posted.

**Comment by idomic** [comment]
@fferegrino any update on this?
We now know that the plugin doesn't work with Jupyter v1 (the version that Sagemaker is running).

**Comment by edublancas** [comment]
We can close this now since we added the `ploomber nb` command in `0.14`, which covers this use case. But @fferegrino, please share your feedback when you get a chance.

More context on Sagemaker integration is here: https://github.com/ploomber/ploomber/issues/454

The new user guide covers the Sagemaker use case: https://docs.ploomber.io/en/latest/user-guide/editors.html#pairing-ipynb-files
