### ISSUE TITLE
Add optional parameter for engine with clients.SQLAlchemyClient 

### ISSUE THREAD

**Issue by reesehopkins** [ploomber/ploomber#426]
Hi, I'm looking into migrating existing workflows to ploomber. In our company, we have some in-house packages to create database connections. It would be nice to pass the engine directly to the SQLAlchemyClient rather than the connection string. We don't save connection strings after the database is initialized. 

Pandas [read_sql_query](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql_query.html?highlight=read_sql_query#pandas.read_sql_query) allows users to pass the connection/engine directly. It would be nice if ploomber provided something similar. Thanks!

#### Example

```python
# clients.py

import foo # in-house library to connect to db
from ploomber.clients import SQLAlchemyClient

def db_connect():
    db = foo.connect_to_db() 
    return SQLAlchemyClient(engine=db) # or it could be a SQLAlchemy connection, whichever is preferred


```

**Comment by edublancas** [comment]
Interesting, do you know if there's any example in SQLAlchemy docs? I've always used with connection strings. I believe it's because of the pooling feature - sqlalchemy may open more connections if it needs to, and it uses the connection string to do so.

What database are you using?

We also have `ploomber.clients.DBAPIClient` that supports passing a function that returns the connection:

https://ploomber.readthedocs.io/en/latest/api/_modules/clients/ploomber.clients.DBAPIClient.html#ploomber.clients.DBAPIClient

**Comment by reesehopkins** [comment]
We use a mix - Oracle, Teradata, Athena -- hence we have an in-house library to connect to the labyrinth of databases. I've used the DBAPIClient and it works great -- after I set `chunksize: null` in the pipeline.yaml. Otherwise, it would chunk parquet and csv files - which I wasn't expecting. I somehow missed it in the [docs](https://ploomber.readthedocs.io/en/latest/get-started/sql-pipeline.html#dumping-data-with-sqldump)

I'm still learning about the capabilities of the SQL clients in ploomber and saw that you recommended the SQLAlchemy client. So far the DBAPI client meets my needs just fine though.

**Comment by edublancas** [comment]
Thanks for your feedback! I'll take a note and improve the docs to ensure that the difference between `DBAPIClient` and `SQLAlchemyClient` is clear! But for the record, we recommend using the latter because it's compatible with other SQL tasks such as [`SQLUpload`](https://ploomber.readthedocs.io/en/latest/api/_modules/tasks/ploomber.tasks.SQLUpload.html#ploomber.tasks.SQLUpload), and  [`SQLTransfer`](https://ploomber.readthedocs.io/en/latest/api/_modules/tasks/ploomber.tasks.SQLTransfer.html#ploomber.tasks.SQLTransfer), but it sounds like `DBAPIClient` will work just fine for your purposes. I'll also ensure we provide proper advice on setting `chunksize`.

Do not hesitate to send any other questions, we're happy to help you through this migration journey. If there are questions that you rather ask privately, please [join our community](https://ploomber.io/community) and message me.
