### ISSUE TITLE
Open as notebook plugin for version 1.2.21 of Jupyter Lab

### ISSUE THREAD

**Issue by luiscapella** [ploomber/ploomber#454]
I am opening a request to see if Ploomber can integrate the "open as notebook" plugin for version 1.2.21 of Jupyter Lab. AWS Sagemaker is currently running Jupyter Lab Version 1.2.21, and I am not sure when the upgrade will happen on the AWS Sagemaker side.

**Comment by idomic** [comment]
Adding a bit more context here:

Sagemaker's Jupyter lab is still version 1, and I am unable to perform an upgrade to version 2 or version 3 of Jupyter lab. And with Ploomber, you want to be able to open the python files as Jupyter notebooks, which I am unable to do with Jupyter lab version 1 (what Sagemaker uses).

They have a pending issue to upgrade Jupyter Lab, since 2020: aws-samples/sagemaker-run-notebook#1
That didn't happened as of last week.

A possible workarounds until we research this issue more are:
The AWS Batch tutorial, I can simply deploy it just like the tutorial (soopervisor - https://soopervisor.readthedocs.io/en/latest/tutorials/aws-batch.html). Once It's done, I can either run it through Batch/Lambda/ECR since it creates already the image for usage.

**Comment by edublancas** [comment]
Hi @luiscapella, thanks for your feedback. We use [jupytext](https://github.com/mwouts/jupytext) for rendering `.py` files as notebooks, I checked their docs and they only support JupyterLab 2.x

However, in our latest release (`0.14`), we added a command that allows pairing `.ipynb` files with `.py` files, so essentially you can work on the `.ipynb` files (and add them to `.gitignore`) and then run a command to sync the changes to the `.py` files.

You can find the user guide here: https://docs.ploomber.io/en/latest/user-guide/editors.html

Note: I'm working on improving the user guide, I'll update this thread once I finish the changes so you can give it a try and let us know if this works for you.

Regarding AWS Batch: yes, that's also a good idea, so I'd say the full workflow would be experiment quickly with Ploomber in Sagemaker, then scale up experiments in AWS Batch.

**Comment by idomic** [comment]
@edublancas this release doesn't work on their public SM version? https://github.com/aws-samples/sagemaker-run-notebook/releases/tag/v0.20.0

**Comment by edublancas** [comment]
Interesting, it should. I'm guessing @luiscapella is running an older version?

**Comment by luiscapella** [comment]
Thanks @edublancas and @idomic! Currently, I am going to complete my use case locally before trying to integrate with Sagemaker again.

**Comment by luiscapella** [comment]
Marking this ticket as closed.

**Comment by edublancas** [comment]
Awesome, feel free to send us any questions you may have!
