### ISSUE TITLE
Stale ploomber versions

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#514]
After checking through pipy stats which versions users use I discovered a gap between the current available version and the one people uses, I was able to see that even though the current version is 0.14.7, some users still leverage really old versions like 0.12.2, 0.7.3 and 0.2.

The goal here is to make sure users gets the best experience and to do that we need to add a version check and display a warning when the version is stale.

**Comment by edublancas** [comment]
a few comments:

we need to be careful to advise on the upgrading procedure since major upgrades introduce breaking changes. some ideas:

* tell the user to upgrade to the latest minor version e.g., if running 0.14, suggest 0.14.X, even if 0.15 is out
* if a new major version is out, we can still tell them to upgrade but maybe auto-generate a list of pinned dependencies in case they break their pipeline and want to roll back (i.e., `pip freeze)
* make sure we don't nag the user too much, there are legit cases where you do not want to upgrade like when running in prod, maybe we can add a field in the config file to turn this off

**Comment by idomic** [comment]
3rd point makes sense.
