### ISSUE TITLE
ploomber install - users sometime find it confusing by having an env inside an env

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#521]
Users install via conda, and then they create another conda/pipenv. In addition when working with samples, the users need to move into the right directory before running the ploomber install (running outside of the dir will error out).

**Comment by edublancas** [comment]
,idea: i think ploomber install should detect if running in a venv

if yes, install inline, otherwise create an env

**Comment by edublancas** [comment]
I'm working on this now, I'm thinking of this workflow:

If running inside a venv -> install in the current environment, otherwise create a new venv

I'm still wondering if this is a good thing to do: If lock files are present, install from them, otherwise, install from regular files. 

Example:

```python
# ds runs it for the first time, this generates lock files, they they commit
ploomber install

# another ds runs this, since lock files exist, it will install from lock files, guaranteeing that the install wont break
ploomber install
```

The idea is that `ploomber install` should just work and do the right thing. but users can still customize its behavior via the cli args. thoughts?

**Comment by idomic** [comment]
Yeah, lock files is not usually used, maybe only in production, I don't think we should enforce users to use them but should give and support the option.
