### ISSUE TITLE
Add parametrized tests for saving/fetching metadata in all products

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#57]
The Product abstract class defines two abstract methods (`fetch_metadata` and `save_metadata`), and each concrete class (such as [File](https://github.com/ploomber/ploomber/blob/09e4b3ad650c66c45814222678afc954b76d1536/src/ploomber/products/file.py#L65)) must implement them. Although the implementation is different for each concrete classes, the interface is the same so we need a parametrized test (using [pytest.mark.parametrize](https://docs.pytest.org/en/6.2.x/parametrize.html)) that checks that all concrete classes implement both methods correctly.

Concrete classes are defined here:
https://github.com/ploomber/ploomber/blob/master/src/ploomber/products/file.py
https://github.com/ploomber/ploomber/blob/master/src/ploomber/products/genericproduct.py
https://github.com/ploomber/ploomber/blob/master/src/ploomber/products/sql.py

**Comment by edublancas** [comment]
No need to do this anymore, handler is determined by the extension

**Comment by idomic** [comment]
@edublancas still relevant?

**Comment by edublancas** [comment]
yeah, we're missing a few unit tests. Not critical though

**Comment by surenzz** [comment]
Hey, I have some specific questions regarding my issue. 

This is an example of a file test I've created:
`def test_save_metadata():
    Path('sample.txt').touch()
    File('sample.txt').save_metadata({"pageNumber": "3"})
    meta = File('sample.txt').fetch_metadata()
    
    assert meta['pageNumber'] == "3"`

- Should I do a series of fetch_metadata() calls to check if its true? (in order to scale with parametrize?) 
- Should I make a different test for fetch_metadata since this is technically doing both?
- Is there a way to see test coverage?
- What is the purpose of .source in the condition? see here: https://github.com/ploomber/ploomber/blob/master/tests/products/test_file.py#L143 

For the GenericProduct class:
- I’m not sure where to begin with running a test here because it’s not being implemented. It’s using an abstract class after inheriting from another class. 
- Line 31, what is happening here? GenericProduct isn’t implementing save_metadata. See here: https://github.com/ploomber/ploomber/blob/master/tests/products/test_genericproduct.py#L31

SQL
- These methods are already tested. How can I get started parametrizing this?

**Comment by idomic** [comment]
Let's pause this work now, we'll assign a new issue to work on since this
is a lower priority.
