### ISSUE TITLE
ploomber examples into local directory

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#620]
When running !ploomber examples -n guides/spec-api-python -o . it outputs an error:

Local copy does not exist...
Cloning into '/root/.ploomber/projects'...
remote: Enumerating objects: 416, done.
remote: Counting objects: 100% (416/416), done.
remote: Compressing objects: 100% (335/335), done.
remote: Total 416 (delta 64), reused 283 (delta 34), pack-reused 0
Receiving objects: 100% (416/416), 1.31 MiB | 8.96 MiB/s, done.
Resolving deltas: 100% (64/64), done.
================= Copying example guides/spec-api-python to ./ =================
Error: '.' already exists in the current working directory, please rename it or move it to another location and try again.

**Comment by Splintdewolfcry** [comment]
I'd like to help to this task

**Comment by edublancas** [comment]
Sure,

So the `ploomber examples` command downloads an example into a directory:

```
ploomber examples some-example -o some-directory
```

we want to give the option for the user to download the example to the current working directory:

```
# downloads to the current working directory
ploomber examples some-example
```

You can see the implementation here: https://github.com/ploomber/ploomber/blob/d8880b5634dafb0d6bf01a161f133490955b2fce/src/ploomber/cli/examples.py#L240

**Comment by edublancas** [comment]
this has a lot of implications: most likely, the current working directory won't be empty, and we should avoid overwriting files as we may delete users' files. so my suggestion would be to only allow this if the folder is empty, but that kind of defeats the purpose since it's hardly likely that a  user will run this in an empty folder. i don't think we should implement this. Feel free to re-open if you think otherwise
