### ISSUE TITLE
nb cli command changes the files without the pipeline.yaml

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#624]
When running on the first pipeline example and running: !ploomber nb -f .ipynb
The files will change from .py to ipynb but the pipeline would keep pointing to the .py files.

This causes:
1. The pipeline isn't functional.
2. Users can revert back to the .ipynb files without changing the file manually.

**Comment by edublancas** [comment]
I don't remember why I didn't implement this when working on the `nb` command. I think it was because if we edit the user's `pipeline.yaml` (to change the extension) with the `yaml` module, the comments are deleted, which is undesirable as the user may have comments that they want to keep.

So the solution should keep them. I saw there is a yaml loading library that supports keeping comments but I don't think we should use that, as it involves adding another dependency.

Using `str.replace('old-path', 'new-path')` should work.

**Comment by idomic** [comment]
Yeah ideally it shouldn't be destructive of comments, replacing only the extension can work instead of loading the whole yml.

**Comment by edublancas** [comment]
https://github.com/ploomber/ploomber/pull/755
