### ISSUE TITLE
ploomber plot with separated products

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#649]
Currently, we can turn products on/off from the plot, but they'll show in the same task node, which makes it hard to read when a task has multiple outputs. Alternatively, we could create new nodes like this:

![Screenshot 2022-03-12 at 08 06 18](https://user-images.githubusercontent.com/989250/158077012-009dc027-6e97-487a-97da-53251bdf796c.png)

**Comment by mitch-at-orika** [comment]
My two cents: products inside the node is ok because that is how the pipeline see's it. My biggest bug bear was that the file path to the products was listed (I dont care about that detail when plotting a summary of my dag). 
something I hacked locally was getting rid of the file path:
https://github.com/ploomber/ploomber/blob/d0a2f32fb79a807aec8dfacc7a5fe57656000792/src/ploomber/dag/dag.py#L1050-L1063
I changed it to:

`def _single_product_short_repr(product):
    s = repr(product)
    print(product)
    if len(s) > 20:
        s_short = str(product).split("\\")[-1] + '\n'
    else:
        s_short = s
    return s_short`

**Comment by edublancas** [comment]
Thanks for your feedback! So if I understand correctly, you only want to see the filename, right?

Actually, I think there's a way to make the task name bold, I was going through graphviz docs and I remember seeing something like that.

**Comment by mitch-at-orika** [comment]
Yeah I think the filename of the product is more insightful than the path to it (although it might just be my pipeline set up where I have long paths). I do now see merit in your idea though if you can get graphviz to draw the connections between individual products and downstream tasks which can vary.  I still think it might be enough for many users without that level of detail and just having the product filenames listed underneath each task node and task dependencies drawn by graphviz. btw, thanks for Ploomber! It is a great tool.
