### ISSUE TITLE
Click version mismatch

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#719]
We've seen some mismatch between the ploomber version and the one sagemaker has with Spacy, Spacy wouldn't get imported because of typer that wouldn't get imported because a dependency on click:

----> 1 import typer
~/anaconda3/envs/mxnet_latest_p37/lib/python3.7/site-packages/typer/__init__.py in <module>
     10 from click.termui import echo_via_pager as echo_via_pager
     11 from click.termui import edit as edit
---> 12 from click.termui import get_terminal_size as get_terminal_size
     13 from click.termui import getchar as getchar
     14 from click.termui import launch as launch
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/home/ec2-user/anaconda3/envs/mxnet_latest_p37/lib/python3.7/site-packages/click/termui.py)

**Comment by edublancas** [comment]
So this  is related to https://github.com/ploomber/ploomber/issues/707

Based on what we've seen this is what I think it's happening:

1. User installs a bunch of packages, and some of them are not compatible with recent versions of click
2. Using an old version of click breaks ploomber because the [package_name](https://github.com/ploomber/ploomber/blob/343a831da26b20467e72da9d2f3ac57256dc1221/src/ploomber_cli/cli.py#L35) argument was added recently
3. They end up with broken environments: they either break some other libraries or ploomber

The solution is to make Ploomber compatible with as many versions as we can, looks like by removing the call to `package_name` things will work. It's fairly easy to fix, I'll take this
