### ISSUE TITLE
CI duplicate executions

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#820]
The CI currently have 2 flags:
on:
push:
pull_request:

We should make sure it doesn't execute twice, creating a resources bottleneck.

**Comment by edublancas** [comment]
wdym? we need both.

I've seen some duplicates when opening PRs but I'm unsure what's the solution

**Comment by idomic** [comment]
There should be a condition that decides which to run instead of running both.
[This](https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012) has a bit more context, not sure if git implemented it.

**Comment by edublancas** [comment]
I went through the link you shared, there isn't any solution at the moment. maybe we should leave it as it is?

**Comment by idomic** [comment]
Yeah I saw it too, we should research perhaps there's someone's custom solution like the one with the key.
The main downside is overhead on commits, when there are 3-4 PRs it will start throttling.

**Comment by Wxl19980214** [comment]
@idomic @edublancas Assigning to me. We have reconstructed the CI/CD but I think the issue persist.  I might be able to skip duplicate CIs, gonna start doing some testing.

**Comment by Wxl19980214** [comment]
Currently from my research, there is no a perfect way of resolving this issue. However, we have this [alternative](https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662). This will prevent triggering the same workflow twice by push and pull_request. 

Downside of this is that push to non-master branch will not trigger workflow. But I think this still works because if someone wants to merge to master, he or she must create a pull request which will trigger workflow.

**Comment by edublancas** [comment]
I saw a PR on soorgeon that connects with this, and added a comment. we can add a wildcard so we can still trigger CI from selected branches https://github.com/ploomber/soorgeon/pull/76#issuecomment-1183708285

**Comment by Wxl19980214** [comment]
@idomic @edublancas  Just tried. It prevents double execution. But the downside is for repo owner, for push to trigger workflow we will have to name the branch dev/*** 

I don't know if people in their forked ploomber repo turns on the github action? I mean if they don't have github action turns on, I don't think this affect anything. Since they will only trigger workflow in ploomber/ploomber repo when they submit a pr and update the pr. I think the only person affected is @edublancas since he is the owner of the repo? If he wants push to trigger, he needs to name the branch dev/***

**Comment by idomic** [comment]
@Wxl19980214 we have it available on soorgeon right? If I open a dev/test branch and a PR will it run?
I think it's an ok solution. @edublancas thoughts?

**Comment by edublancas** [comment]
yeah. I think this is an ok solution. let's document it in contributing.md

and let's also document the ok-to-test command in the contributing.md
