### ISSUE TITLE
fix performance issues in jupyter plug-in

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#894]
from Slack:

> Hey All, I am having troubles where ploomber seems to be trying to build my incomplete pipeline over and over again as soon as I start a jupyter notebook server and while I am trying to write the code in jupyter. As soon as I start the server the prompt just fills up with ==== DAG render with warnings === , NotebookRunner: etc etc and it just plots the same thing over and over again. The main issue is it seems to be stealing all the resources and it makes the notebooks where I am writing the code extremely slow. I have tried running "jupyter serverextension disable ploomber" but that doesnt stop the issue. Is there some best practice way I am missing here? When you are writing code for individual components in the same environment and folder as where you want your pipeline code to be. Why does it start trying to do things before I call ploomber build etc can you pause it trying to constanly run the pipeline?? OR should I uninstall ploomber or something?

notes:

* the user has a folder with pipelines. I don't think this would make a different since we only parse the first pipeline that we find but still adding it here to take it into account
* running ploomber 0.19.7
* pipeline is not very large

**Comment by mitch-at-orika** [comment]
So (in case it helps) from the moment I start the server (in the directory where the pipeline.yaml file is located the server command prompt is printing the below pattern in a non stop loop:

**********

============================================== DAG render with warnings ===============================================
# for each task:
- NotebookRunner: 'TASK NAME' -> MetaProduct({'TASK NAME': File('product FILENAMES'}}
-------------------------------- TASK FILE NAME 

================================================== Summary (4 tasks) ==================================================
# for each task:
NotebookRunner: 'TASK NAME' -> MetaProduct({'product FILENAMES'

============================================== DAG render with warnings ===============================================

  warnings.warn(str(warnings_))
[I 2022-07-09 17:54:02.821 ServerApp] [Ploomber] Using dag defined at: 'PATH TO PIPELINE.YAML'
[I 2022-07-09 17:54:02.822 ServerApp] [Ploomber] Pipeline mapping keys: 'RELATIVE PATHS TO TASKS'
[I 2022-07-09 17:54:02.841 LabApp] Build is up to date

C:\path_to\ploomber\spec\dagspec.py:393: UserWarning: The following placeholders are declared in the environment but unused in the spec: {'placeholder vars im not using yet'}
  warnings.warn('The following placeholders are declared in the '
C:\path_to\ploomber\dag\dag.py:444: UserWarning:

*****************

This will just repeat forever. I am not 100% sure what it is doing but it slows the server down substancially. At the moment my work around is to rename the pipeline.yml to get it to stop. But it is annoying because I need the cell injections to operate.. so I change it back open it and then rename again.

**Comment by mitch-at-orika** [comment]
I think you've done it! jupyter is back to being fast all the messages about DAG render etc just happen once then stop. there is a couple of errors in the prompt: 
RuntimeError: Cannot enter into task <Task pending name='Task-7' coro=<HTTP1ServerConnection._server_request_loop() running at envpath\lib\site-packages\tornado\http1connection.py:825> wait_for=<Future finished result=b'GET /static...2 GMT\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at envpath\lib\site-packages\tornado\ioloop.py:687]> while another task <Task pending name='Task-686' coro=<PeriodicCallback._run() running at envpath\rn\lib\site-packages\tornado\ioloop.py:921> cb=[IOLoop.add_future.<locals>.<lambda>() at envpath\lib\site-packages\tornado\ioloop.py:694]> is being executed. It did crash my explorer in lab once but a refresh fixed it. Thanks for looking into this and looking forward to next release!

**Comment by edublancas** [comment]
Awesome, thanks for confirming this works! (The error you shows looks non-Ploomber related)

I still need to do a few tweaks, but it'll be part of the next release!
